### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by cloudcdh** [Area69Lab/Ubuntu-SSH#3]
Hi, I've been through Area69Lab repositories and thank you guys for those nice projects. 
I was also trying to make something work in actions but I'm not able to complete the project. This is about socks5 proxy which can be used with shadowsocks, so can you guys check if it can be deployed with git actions.

Useful  repositories
https://github.com/shadowsocks/shadowsocks-libev
https://github.com/cloudcdh/vsocks5
Hopefully waiting for your replay. 
(I sent an email to manofuranium@gmail.com last month but got no replays that's why requesting here )

Thankyou

**Comment by techyminati** [comment]
Hey Thanks for your Appreciation ! I would like to inform
, You Can Contact us on telegram at https://t.me/Area69Lab , So we can help you Further
