### ISSUE TITLE
Error: Error: 100

### ISSUE THREAD

**Issue by qthang** [Area69Lab/Ubuntu-SSH#4]
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' no longer has a Release file.
Error: Error: 100

Can you fix it? Thank you!

**Comment by rokibhasansagar** [comment]
The Workflow uses Ubuntu Runner, and you are talking about OpenSUSE Container.
That makes the issue as Unrelated and Invalid.

**Comment by rokibhasansagar** [comment]
@qthang,
Yet, if you could explain what you are trying to do with it, supplementing with logs of course, only then we might help you in your case.

**Comment by rokibhasansagar** [comment]
@qthang 
I see that you were referring to `apt update` issue.

All you had to do is clean apt caches using `sudo apt autoclean && sudo apt autoremove` and then `sudo apt update` again to resolve the issue.
